steps:
  # Construir la imagen
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/spsa-marketing-prd/web-mkt-repositorio/web_mkt_viv_aperturapardo_registroclientes:$SHORT_SHA"
      - "."

  # Publicar la imagen
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/spsa-marketing-prd/web-mkt-repositorio/web_mkt_viv_aperturapardo_registroclientes:$SHORT_SHA"

  # Desplegar en Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "web_mkt_viv_aperturapardo_registroclientes"
      - "--image=us-central1-docker.pkg.dev/spsa-marketing-prd/web-mkt-repositorio/web_mkt_viv_aperturapardo_registroclientes:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--service-account=sa-cloudrun-eventos@spsa-marketing-prd.iam.gserviceaccount.com"
      - "--port=8080"

images:
  - "us-central1-docker.pkg.dev/spsa-marketing-prd/web-mkt-repositorio/web_mkt_viv_aperturapardo_registroclientes:$SHORT_SHA"  